---
rekor:
  server:
    securityContext:
      runAsNonRoot: true
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      hosts:
      # replace with cluster domain
        - host: rekor.apps.177ca20f62c2a845e53e.hypershift.aws-2.ci.openshift.org
          path: /

trillian:
  enabled: true

fulcio:
  namespace:
    name: fulcio-system
    create: false
  createcerts:
    enabled: false
  server:
    secret: fulcio-secret-rh
    securityContext:
      runAsNonRoot: true
    ingress:
      http:
        annotations:
          route.openshift.io/termination: "edge"
        className: ""
        hosts:
          # replace with cluster domain
          - host: fulcio.apps.177ca20f62c2a845e53e.hypershift.aws-2.ci.openshift.org
            path: /
  config:
    contents:
      OIDCIssuers:
        # replace
        ? https://keycloak-keycloak-system.apps.177ca20f62c2a845e53e.hypershift.aws-2.ci.openshift.org/auth/realms/sigstore
        : IssuerURL: https://keycloak-keycloak-system.apps.177ca20f62c2a845e53e.hypershift.aws-2.ci.openshift.org/auth/realms/sigstore
          ClientID: sigstore
          Type: email

tuf:
  enabled: true
  secrets:
    rekor:
      name: rekor-public-key
      path: rekor-pubkey
    fulcio:
      name: fulcio-secret-rh
    ctlog:
      name: ctlog-public-key
      path: ctlog-pubkey
  ingress:
    className: ""
    annotations:
      route.openshift.io/termination: "edge"
    http:
      hosts:
        # replace with cluster domain
        - host: tuf.apps.177ca20f62c2a845e53e.hypershift.aws-2.ci.openshift.org
          path: /

ctlog:
  enabled: true
  createctconfig:
    logPrefix: sigstorescaffolding
    backoffLimit: 30

copySecretJob:
  enabled: true
  backoffLimit: 1000

tsa:
  enabled: false
