apiVersion: batch/v1
kind: Cronjob
metadata:
  name: {{ .Values.configs.segment-backup-job.name }}
spec:
  schedule: "0 0 * * *"  
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:                  
    spec:
      template:
        serviceAccountName: segment-backup-sa
        metadata:
          labels:               
            parent: "segment-backup-job"
        spec:
          containers:
          - name: {{ .Values.configs.segment-backup-job.name }}
            image: "{{ .Values.configs.cosign_deploy.image.registry }}/{{ .Values.configs.cosign_deploy.image.repository }}:{{ .Values.configs.cosign_deploy.image.version }}"
            command: ["/bin/bash",  "/opt/app-root/src/script.sh"]
          restartPolicy: OnFailure 