---

# No-Fail steps to get a working sigstore stack with a fresh OpenShift cluster
# 0) obtain the base_domain with:
#       oc get dns/cluster -o jsonpath='{ .spec.baseDomain }' && echo
# 1) ./fulcio-create-root-ca-openssl.sh  (interactive, you'll enter "apps.<base_domain>" for the hostname, and enter the same password for all keys"
# 2) ./rekor-create-signer-key.sh
# 3) substitute base_domain from above (rosa.***.com) in 5 places in this file, like so in VIM :) 
#         :%s/rosa.*.com/rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com/g
# 4) Run the following:
#          helm upgrade -i scaffolding --debug . -n sigstore --create-namespace -f examples/values-rosa-upstream-images.yaml
#
#          A good way to tell if things are progressing well is to watch 'oc get jobs -A' and when the tuf-system job is complete, things should be ready.
#          Once complete, move to the ./sign-verify.md to sign/verify artifacts

configs:
  fulcio:
    server:
      secret:
        name: fulcio-secret-rh
        password: "secure"
        public_key_file: "keys-cert/file_ca_pub.pem"
        private_key_file: "keys-cert/file_ca_key.pem"
        root_cert_file: "keys-cert/fulcio-root.pem"
  rekor:
    signer:
      secret:
        name: rekor-private-key
        private_key_file: "keys-cert/rekor_key.pem"

scaffold:
  ctlog:
    namespace:
      create: false
    server:
      image:
        registry: quay.io
        repository: securesign/ct_server
        version: sha256:fa5a9a55884d09b7d3fc1d2390087f8344962398d90234958ca7424354c6909e
        pullPolicy: IfNotPresent
    createctconfig:
      backoffLimit: 30
      enabled: true
      initContainerImage:
        curl:
          registry: registry.access.redhat.com
          repository: ubi9/ubi-minimal
          version: sha256:dc02c6aa8199beb8ed13312d7116a94aa87b5412886bbe358845d3f0626c0f1e
          imagePullPolicy: IfNotPresent
      image:
        registry: quay.io
        repository: securesign/createctconfig
        version: sha256:1888f625d93618e32766e712f94e148f72fb82b11604001cd98ea6300a9197be
        pullPolicy: IfNotPresent
    createtree:
      image:
        registry: quay.io
        repository: securesign/createtree
        version: sha256:c03cdc797e8d248bfa7371b34b1eda582702e5386fdbb543e5a121afae255fb7
        pullPolicy: IfNotPresent
  fulcio:
    namespace:
      name: fulcio-system
      create: false
    createcerts:
      enabled: true
      image:
        registry: quay.io
        repository: securesign/createcerts
        version: sha256:cc10d4f86a893de36e6a269558612b1343dc64c359b927cfcc77ba617eab8283
        pullPolicy: IfNotPresent
    server:
      image:
        registry: quay.io
        repository: securesign/fulcio
        version: sha256:9239e56419073d57bba2ec217c0cf64499b7d4e686a875394d34a802ad99fbad
        pullPolicy: IfNotPresent
      secret: fulcio-secret-rh
      ingress:
        http:
          enabled: true
          className: ""
          annotations:
            route.openshift.io/termination: "edge"
          hosts:
          - host: fulcio.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com
            path: /
    config:
      contents:
        OIDCIssuers:
          # https://<keycloak_instance>.<keycloak_ns>.<base_domain>/auth/realms/sigstore
          ? https://keycloak-keycloak-system.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com/auth/realms/sigstore
          : IssuerURL: https://keycloak-keycloak-system.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com/auth/realms/sigstore
            ClientID: sigstore
            Type: email

  rekor:
    namespace:
      namespace: rekor-system
      create: false
    server:
      image:
        registry: quay.io
        repository: securesign/rekor-server
        version: sha256:90797567a064e7b7a41fde208c8468decd11b6b9bab8ed4ab60139c8667600db
        pullPolicy: IfNotPresent
      signer: /key/private
      signerFileSecretOptions:
        secretName: rekor-private-key
        secretMountPath: /key
        secretMountSubPath: private
        privateKeySecretKey: private
      ingress:
        className: ""
        annotations:
          route.openshift.io/termination: "edge"
        hosts:
          - host: rekor.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com
            path: /
          
    createtree:
      image:
        registry: quay.io
        repository: securesign/createtree
        version: sha256:c03cdc797e8d248bfa7371b34b1eda582702e5386fdbb543e5a121afae255fb7
        pullPolicy: IfNotPresent
    backfillredis:
      image:
        registry: quay.io
        repository: securesign/backfill-redis
        version: sha256:e2cecc21e04f7234dd46651b8cba6a076d869197aa84044404bc08339d6e4913
        pullPolicy: IfNotPresent
  trillian:
    namespace:
      create: false
    createdb:
      image:
        registry: quay.io
        repository: securesign/createdb
        version: sha256:19917392e462b0dcf9550441ec0da9518b4666de28fb7e992c692b624569488e
        pullPolicy: IfNotPresent
    initContainerImage:
      netcat:
        registry: quay.io
        repository: securesign/netcat
        version: sha256:b07e50992406ec494abaf2e32d6184f947735074503d6842b4f98240846dc705
      curl:
        registry: registry.access.redhat.com
        repository: ubi9/ubi-minimal
        version: sha256:dc02c6aa8199beb8ed13312d7116a94aa87b5412886bbe358845d3f0626c0f1e
        imagePullPolicy: IfNotPresent
    redis:
      args:
        - /usr/bin/run-redis
        - --bind
        - 0.0.0.0
        - --appendonly
        - "yes"
      image:
        registry: registry.redhat.io
        repository: rhel9/redis-6
        version: "sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94"
        pullPolicy: IfNotPresent

    logSigner:
      image:
        registry: quay.io
        repository: securesign/trillian_log_signer
        version: sha256:ba8d467c38c1eb6a24f843b855e6b01fd5b524d7db45a82b4092a681b561c143
        pullPolicy: IfNotPresent
    logServer:
      image:
        registry: quay.io
        repository: securesign/trillian_log_server
        version: sha256:7e4e931b0141d82034700d7aab113d5b1aab8b2af79fbd254a7a5958cd601969
        pullPolicy: IfNotPresent
    mysql:
      gcp:
        scaffoldSQLProxy:
          registry: quay.io
          repository: securesign/cloudsqlproxy
          version: sha256:6ebd895c0d9896d27185d5e44e2fddd0d00733c5417646b5b239ecfd33bc9bdb
      image:
        registry: quay.io
        repository: securesign/trillian-db
        version: sha256:090e44f8982d66d21c6dc74eb3c0ab3c17e43f22f11731f2e15463f39f811c4a
        pullPolicy: IfNotPresent
      args: []
      securityContext:
        fsGroup: 0
      livenessProbe:
        exec:
          command:
          - mysqladmin
          - ping
          - -h
          - localhost
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
      readinessProbe:
        exec:
          command:
          - mysqladmin
          - ping
          - -h
          - localhost
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
  tuf:
    namespace:
      create: false
    secrets:
      fulcio:
        name: fulcio-secret-rh
    enabled: true
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      http:
        hosts:
          - host: tuf.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com
            path: /
    deployment:
      registry: quay.io
      repository: securesign/tuf/server
      version: sha256:b1cbb379f5c4b315bc5a7d7a37865ab61669a0a07002b6920374ebae3b37699c

  copySecretJob:
    enabled: true
    backoffLimit: 1000
