---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: scaffold
  releaseName: scaffolding
  valuesFile: values.yaml
  repo: https://sigstore.github.io/helm-charts
  version: 0.6.14
resources:
  - ./namespaces
  - ./rbac/rolebindings
