trillian:
  enabled: true
  createdb:
    image:
      registry:  gcr.io
      repository: trillian-opensource-ci/db_server
      version: "sha256:22b7fddcb4bafc5692760d84dca5e86294363a94e8f0ecb8f5c39364d436e6d5"
  initContainerImage:
    netcat:
      registry: quay.io
      repository: rcook/netcat
      version: v1.0.0
    curl:
      registry: registry.access.redhat.com
      repository: ubi9/ubi-minimal
      version: latest
      imagePullPolicy: IfNotPresent
  namespace:
    name: trillian-system
    create: false
  logserver:
    image:
      registry: quay.io
      repository: rcook/trillian_log_server
      version: v1.2.2
  logsigner:
    image:
      registry: quay.io
      repository: rcook/trillian_log_signer
      version: v1.2.2


rekor:
  namespace:
    name: rekor-system
    create: false
  server:
    image:
      registry: quay.io
      repository: rcook/rekor-server
      version: v1.2.2-dirty
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      hosts:
        #- host: rekor.<base_domain>
        - host: rekor.apps.rosa.e4kun-p6j9t-fkp.1u73.p3.openshiftapps.com
          path: /
          
  redis:
    image:
      registry: registry.redhat.io
      repository: rhel9/redis-6
      pullPolicy: IfNotPresent
      version: "sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94"

  initContainerImage:
    curl:
      registry: registry.access.redhat.com
      repository: ubi9/ubi-minimal
      version: "latest"
      imagePullPolicy: IfNotPresent

fulcio:
  namespace:
    name: fulcio-system
    create: false
  createcerts:
    enabled: true
  server:
    image:
      registry: quay.io
      repository: rcook/fulcio
      version: v1.3.1
    secret: fulcio-secret-rh
    ingress:
      http:
        annotations:
          route.openshift.io/termination: "edge"
        className: ""
        hosts:
         #- host: fulcio.<base_domain>
          - host: fulcio.apps.rosa.e4kun-p6j9t-fkp.1u73.p3.openshiftapps.com
            path: /
  config:
    contents:
      OIDCIssuers:
        # https://<keycloak_instance>.<keycloak_ns>.<base_domain>/auth/realms/sigstore
        ? https://keycloak-keycloak-system.apps.rosa.e4kun-p6j9t-fkp.1u73.p3.openshiftapps.com/auth/realms/sigstore
        : IssuerURL: https://keycloak-keycloak-system.apps.rosa.e4kun-p6j9t-fkp.1u73.p3.openshiftapps.com/auth/realms/sigstore
          ClientID: sigstore
          Type: email

tuf:
  deployment:
    registry: quay.io
    repository: ablock/tuf-server
    version: "sha256:c4f534807b331e97b107d908b7e0cf14a896399bc372bca6a2c7e4f6d730807c"
  namespace:
    name: tuf-system
    create: false
  secrets:
    fulcio:
      name: fulcio-secret-rh
  enabled: true
  ingress:
    className: ""
    annotations:
      route.openshift.io/termination: "edge"
    http:
      hosts:
        #- host: tuf.<base_domain>
        - host: tuf.apps.rosa.e4kun-p6j9t-fkp.1u73.p3.openshiftapps.com
          path: /

ctlog:
  namespace:
    name: ctlog-system
    create: false
  enabled: true
  server:
    image:
      registry: quay.io
      repository: rcook/ct_server
      version: v0.6.4-dirty
  createctconfig:
    logPrefix: sigstorescaffolding
    backoffLimit: 30

copySecretJob:
  enabled: true
  backoffLimit: 1000
