apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  finalizers:
  - user.cleanup
  labels:
    app: sso
  name: jdoe
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    email: jdoe@redhat.com
    enabled: true
    firstName: Jane
    lastName: Doe
    username: jdoe
